/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_BigIT_p2p_p2p */

#ifndef _Included_com_BigIT_p2p_p2p
#define _Included_com_BigIT_p2p_p2p
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_BigIT_p2p_p2p
 * Method:    p2pinit
 * Signature: (Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_BigIT_p2p_p2p_p2pinit
  (JNIEnv *, jclass, jobject, jstring, jint, jstring, jint, jstring, jstring);

/*
 * Class:     com_BigIT_p2p_p2p
 * Method:    p2pconnect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_BigIT_p2p_p2p_p2pconnect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_BigIT_p2p_p2p
 * Method:    p2paccept
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_BigIT_p2p_p2p_p2paccept
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_BigIT_p2p_p2p
 * Method:    p2psend
 * Signature: (Ljava/lang/String;[BI)I
 */
JNIEXPORT jint JNICALL Java_com_BigIT_p2p_p2p_p2psend
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     com_BigIT_p2p_p2p
 * Method:    p2pdisconnect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_BigIT_p2p_p2p_p2pdisconnect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_BigIT_p2p_p2p
 * Method:    p2pclose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_BigIT_p2p_p2p_p2pclose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
